### ISSUE TITLE
Assignment 8-5

### ISSUE THREAD

**Issue by Ailrun** [snu-sf-class/pl2016#70] opened 2016-05-02 06:49 UTC
In P05, we need to prove that our definition of 's_compile'.
To do that, problem requires the definition of 's_execute'.

However, in 's_execute', there is some inconsistency between 'SPlus', 'SMinus' and 'SMult'.
When 'SPlus' and 'SMinus' take '[]' stack, then they return '[]', where 'SMult' takes '[]' then returns 's_execute st stack prog''.

Is there some typo in D.v?

**Comment by jeehoonkang** [comment] 2016-05-02 07:12
- Duplicate of https://github.com/snu-sf-class/pl2016/issues/68#issuecomment-216108999
- I will answer there.  Thank you for the issue!

**Closed as completed by jeehoonkang** 2016-05-02 07:12 UTC
